### ISSUE TITLE
dmv.ca.gov doesn't work

### ISSUE THREAD

**Issue by brkorb** [jswanner/DontF-WithPaste#102]
They are able to detect a paste despite this addon.

**Comment by jswanner** [comment]
@brkorb, is the extension active for that site? (Is the extension's icon blue?)

If so, can you be more specific about where you had problems with paste?

I checked the site briefly for forms, the only form I came across with a field that blocked paste was their email confirmation field on the [account registration form](https://www.dmv.ca.gov/mga/sps/authsvc?PolicyId=urn:ibm:security:authentication:asf:dmvUscAccountCreate), and this extension did circumvent their paste blocking.

**Comment by brkorb** [comment]
It did for me, too. But not for entering the bank routing number or account
number. To get to that page, you have to actually be trying to "buy"
something on the site (like registration renewal). I typed it in.

 - Bruce

**Comment by jswanner** [comment]
As I'm not a CA resident, I can't get into that part of their application.

Do you know if the payment form was still on the dmv.ca.gov domain or if you were directed elsewhere to collect payment?

It's possible in addition to blocking `paste` events they are also intercepting the keyboard events associated with that action, and if that's the case this extension does not circumvent that kind of heavy handed interference by the website authors (but using Edit -> Paste from the browser's menu should still work).

**Comment by brkorb** [comment]
OK. I'll give that a try next year.
BTW, it _looked_ like it was the dmv.ca.gov domain, but there are
always frames. So I don't really know.
You can get an account there without being a resident, but you won't
be able to "buy" anything without having either a CA driver's license
or a CA registered vehicle.

 - Bruce

**Comment by danielg4** [comment]
I don't know what you people are on, but I just went to the CA DMV's website in Chrome with no extension at all, got to the page where one enters routing and account number, and while it did indeed block Ctrl-V in the bank number fields (but not in other fields on the page), Paste from the right-click menu still worked perfectly for them. Again, this was with no extension at all.

**Comment by brkorb** [comment]
It is entirely possible that not everyone bothers with the right click 
menu item when they know that Ctl-V should work. Thank you for your 
snotty additional information.

**Comment by danielg4** [comment]
Well, be that as it may, this conversation is on a trouble ticket of a browser extension for which the documentation clearly states that it DOES NOT make Ctrl-V work, nor does it make the right-click menu work for that matter, only that it makes Paste from the three-dot/hamburger menu work, which by the way also worked with no extension in the above test. You may call it snotty, but people have a right to be irritated with those who don't bother to simply read.

**Comment by jswanner** [comment]
Ah, good information to know.

This extension does not interfere with keyboard shortcuts, or the blocking thereof. It circumvents blocking of copy, cut, & paste functionality directly, meaning it'll allow you to use Edit -> Paste, or paste from the context menu (right click, assuming that's not blocked).
