### ISSUE TITLE
Airmiles: Doesn't work with airmiles

### ISSUE THREAD

**Issue by YesTrustMe** [jswanner/DontF-WithPaste#123]
https://airmilescardlink.ca/link
or try this: https://airmilescardlink.ca/#enrolFormPosition

**Comment by jswanner** [comment]
@YesTrustMe, that site is blocking paste functionality, and this extension is circumventing their blocking. Unfortunately, they are also listening for the keyboard shortcut for paste and interfering with paste that way as well. This extension does not event listeners for key presses, and therefore cannot undo that aspect of paste blocking. You are able to paste on their site, but either need to right click on the input field and then choose "Paste" or do so from the browser's "Edit" menu.
