### ISSUE TITLE
fails on https://www.treasurydirect.gov/RS/PW-Display.do

### ISSUE THREAD

**Issue by larham** [jswanner/DontF-WithPaste#125]
Icon shows the extension to be enabled, but pasting fails on https://www.treasurydirect.gov/RS/PW-Display.do

**Comment by jswanner** [comment]
@larham, I'm not able to get to that page to figure out what's going on. The pages I can get to with forms (https://www.treasurydirect.gov/RS/RSGatewayRW & https://www.treasurydirect.gov/RS/UN-Display.do) are not blocking paste.

One thing to note, if the site is also interfering with the keyboard shortcuts associated to those actions this extension doesn't fix that. Hopefully, you are still be able to paste from the context menu (right click) or from the Edit menu.

**Comment by jswanner** [comment]
Oh, I realized this page has come up before: https://github.com/jswanner/DontF-WithPaste/issues/78

If it's still that virtual keyboard thing they have on that site, I don't think there's anything this extension can do to help you. Maybe Tampermonkey can help with this?

**Comment by larham** [comment]
Thanks for the reply, the previous consideration for this, and the tool itself.

Indeed, the idea of changing a 'readonly' attribute is invasive, and thanks for the reference to use a different tool to accomplish that. 

Looks like the treasury got sold on the "security" of a virtual keyboard. Here's the offending segment of HTML source:

`

  | <td  valign="top">
  | <script type="text/javascript">
  | document.write("<input type=\"password\" autocomplete=\"off\" readonly=\"readonly\" name=\"password\" id=\"password\" size=\"30\" maxlength=\"64\" class=\"pwordinput\" value=\"\" />");
  | </script>
  |  
  | <noscript>
  | <input type="password" name="password" id="password" class="pwordinput" size="30" maxlength="64" value="" autocomplete="off" />
  | </noscript>
  |  
  | </td>
`


p.s., before posting, I searched for "treasury" among all issues, i.e.  [this search](https://github.com/jswanner/DontF-WithPaste/issues?q=is%3Aissue+sort%3Aupdated-desc+treasury)
and silly Github didn't find the existing issue. Does github just search for whole 'words', missing hits like "treasurydirect"? I'm sad; sorry I didn't find the existing discussion.
