### ISSUE TITLE
[feature request] clear copy without appendages

### ISSUE THREAD

**Issue by gendalv** [jswanner/DontF-WithPaste#126]
some sites append copyright and other garbage text when they detect a copy

**Comment by jswanner** [comment]
@gendalv, if the site is amending the copied content via the standard `copy` event and this extension is enabled on that site, then this should already be taken care of. If that's not the case, if it's a public site you are experiencing this on, can you share the URL?

**Comment by gendalv** [comment]
@jswanner livemaster.ru when copying info from any product page it appends site link and ©️

**Comment by jswanner** [comment]
@gendalv, if you [enable the extension for that site](https://github.com/jswanner/DontF-WithPaste#usage), it does prevent it from injecting that additional content into the copied text.

**Comment by gendalv** [comment]
@jswanner I didn't realize it was manual/white list type of extension.
